### ISSUE TITLE
Adding devices to group allows only 1 device

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/argos#101]
The join to group adds only the first device in the stack. 

![Screenshot from 2024-12-05 09-24-07](https://github.com/user-attachments/assets/7c42fa98-a0d3-4b36-87cb-acece4ddaf69)

**Comment by erasta** [comment]
right click on the group icon (the splitted upward arrow) will now show the following menu.
also, now adding the top of the stack to be contained does not remove it from the stack, if you want that feature, reopen this issue.
![image](https://github.com/user-attachments/assets/740e53e4-b9ea-4d85-b715-25c8d136606f)
