### ISSUE TITLE
Multi sensor at one point

### ISSUE THREAD

**Issue by NirInbal** [KaplanOpenSource/argos#106]
What is the best way to handle a point with many different measuring instruments at the point (a meteorological station with many different sensors on it, for example)?
Display a symbol of meteorological station on the map, for example, and if you point with the mouse on that point, you see the devices connected to it.
In any case, it would be useful if, in the legend, a list of devices connected to the meteorological station would appear.

**Comment by yehudarav** [comment]
To make a group of them. 

Maybe we need a better control over the devices once they are in the group, for example enable editing.
