### ISSUE TITLE
Show trial-dependent properties for devices in table format 

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/argos#87]
The table format of the devices does not allow for the editing of the trial-dependent properties.

**Comment by yehudarav** [comment]
![Screenshot from 2024-10-11 12-45-33](https://github.com/user-attachments/assets/d14d01b4-17d2-4e48-843d-acaa5de3c917)

I mean in this interface. I know you can see all of then in the right panel, but its not exactly a table format. 
This interface is very comfortable.

**Comment by erasta** [comment]
![image](https://github.com/user-attachments/assets/096f93f1-dfc1-45b1-abc3-511195ddbc71)
Done
