### ISSUE TITLE
How do I add polygons? 

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/argos#88]
I cant find the interface to add the polygons? 

Did the polygons (with names) also include addition of lines/arcs? 
Can we show the distance on it?

**Comment by erasta** [comment]
![image](https://github.com/user-attachments/assets/2439eede-0e31-4fb0-a5ca-2540da613b0f)
you can press the add polygon / circle buttons near the shapes, then draw the polygon on the map.
switching between polyline and polygon is done on the combo `type`.
arcs and lines are not yet implemented, do you want those?

**Comment by yehudarav** [comment]
Clicking the plus does not add a new circle (I succeeded but prob clicked more than once).

**Comment by yehudarav** [comment]
Is it possible to add distances (with tuggle?)

**Comment by erasta** [comment]
![Screenshot from 2024-10-22 18-08-42](https://github.com/user-attachments/assets/4f0d719b-4a2b-48ad-a30b-60389f18756c)
added an info message at the bottom, showing distance when applicable
we'll do something more stylish later on

**Comment by yehudarav** [comment]
Cool
