### ISSUE TITLE
Problem with uploading using CSV

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/argos#92]
The file (sent to you in email) should work for the Jerusalem experiment. 
However, it does not work. 

Is it possible to update the interface, such that it will ask the user to assign the right column on 
each column in the CSV file?

**Comment by erasta** [comment]
Solved the problem, it was a but in the upload, not related to the column names.
Also, I can add the interface as you asked if you want.
![image](https://github.com/user-attachments/assets/d8edc140-48d9-4e3d-9f9f-7d7589e568a2)

**Comment by erasta** [comment]
done
![image](https://github.com/user-attachments/assets/4ad5a5c7-2882-47da-8bc9-30d80e746910)
