### ISSUE TITLE
The CSV upload does not work. 

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/argos#93]
The CSV upload does not work. 

![upload](https://github.com/user-attachments/assets/31d3813e-ebf4-409b-83e8-c6f0cb86d36c)

If I give it a CSV file without the station name, it just warns me about it. When we add the column nothing happens. 

I though we built a gui to select the columns from the file. Therefore, the user does not need to know 
what are the names of the columns that you use. 

I have attached a csv file that I used. 
Test it in the IMS experiment. 

[test.csv](https://github.com/user-attachments/files/18018264/test.csv)

**Comment by erasta** [comment]
![image](https://github.com/user-attachments/assets/11618223-9733-49ef-bc5a-40ad712102fb)
ability to select type and name implemented
