### ISSUE TITLE
Show device coordinates and allow editing 

### ISSUE THREAD

**Issue by yehudarav** [KaplanOpenSource/argos#98]
Currently the editing of the devices in the tables does not allow the user to edit the coordinates.

**Comment by yehudarav** [comment]
Actually, there isn't (accessible) place to edit the location of a single (or of the selected) devices manually.

**Comment by erasta** [comment]
![image](https://github.com/user-attachments/assets/443f2162-a103-4ef2-b9c7-a70ce30d6692)
also on the device tabular view
